### ISSUE TITLE
Compression compatible with Content-Encoding: gzip?

### ISSUE THREAD

**Issue by magma1447** [pramsey/pgsql-gzip#11]
I am trying to solve an issue where an ajax call in a site runs out of memory, even when allowed 256 MB. It happens in PHP's pg_fetch_assoc(). Obviously I could increase the amount of RAM more, but I rather not. I have the idea to compress the data and set the header `Content-Encoding: gzip`. Obviously I can't compress the data with PHP since I can't fetch it, but if I compress it inside the DB engine it should be solved, which would be a great solution in this case. Normally I would rather try to move resource heavy processes away from the DB engine since it's harder to scale up than the PHP part, but in this specific case it feels like the proper solution.

I installed this extension, added a header() and added gzip() to the SQL query. No luck.

My guess is that this gzip() function adds some headers, in the same way that [gzencode](https://www.php.net/manual/en/function.gzencode.php) does. To make it work with PHP I need to use [gzcompress](https://www.php.net/manual/en/function.gzcompress.php) which doesn't have headers.

I am not a C developer but it didn't sound impossible, so I started investigating the code. I assume it's WINDOW_BITS|GZIP_ENCODING in the pg_gzip() function that needs to be something else than 31. I tried to read up on it but didn't get too sure of what it needed to be. 15? -15? -31? Anyway, felt like it was easiest to just adjust the code, make, make install, drop extension, create extension. But no.

For some reason it doesn't seem like my adjusted code changes anything. I assume that it doesn't get installed properly and that PostgreSQL is still using the first version. I have tried to Google about it, but couldn't find any way to force it to update.

To prove to myself that my code change didn't work I changed the compression_level variable into a hard coded 1 and then a 9. The length of a gzipped 100 MB long string was the same regardless. When using the compression level parameter it changes.

So three questions:
1) Would the author be interested in providing a compression function compatible with the http protocols gzip/PHPs gzcompress?
2) Do you know what I actually need to change? And if I am trying to change the right thing, do you know what value?
3) What can I do to actually make my code changes work? I understand that's probably more of a PostgreSQL question, but I figure an extension developer might know. For the record I have not tried restarting PostgreSQL. I currently have a query that has been running for 18 days, the ETA is ~23 days. I don't want to abort the query right now.

Or have I just missed something else and am completely wrong here?

**Comment by pramsey** [comment]
I think you've just missed something. The gzipped output is represented by PgSQL as a bytea, which will come back to you in a standard cursors as **hex encoded text**. You are going to need to either use a binary cursor in your query (not sure of PHP will even let you do that) or convert the hex back to 8-bit bytes in your PHP. The fact that you're going to get 2x data size over the wire might also invalidate your hope that you can sidestep size issues using compression. (That's a whole different discussion, but if you're hitting limits in size then "I'll just compress it" is clearly only a stopgap until some object comes along that is **still too big** even after compression. You might want to go back to first principles to solve the core problem.)

**Comment by magma1447** [comment]
Number 3 has been resolved. I now know how to make the code changes work. I needed to restart the psql cli client. Found help on IRC #postgresql with that.

**Comment by magma1447** [comment]
@pramsey Thank you for your prompt reply. I missed that you had replied before my other one.

I am not super familiar with PostgreSQL so I totally missed that it was hex encoded text. I thought that was some CLI magic in the client. But if I can't get the binary compressed string from PostgreSQL my idea won't work. Now you have given me something to look into. Hopefully I will understand the problem better soon, it's just that lack of PostgreSQL knowledge, but the more you read and test, the more you learn.

The problem won't grow. It's more or less fixed forms of data that can be fetched, so it is a good solution, theoretically. It's a handful of polygons in a database with almost a million of them.

**Comment by magma1447** [comment]
To anyone who finds this thread via Google or otherwise, I want to present my solution.

While the following required more than 256 MB of ram:
```
$res = pg_query("SELECT ST_AsGeoJSON(geom)");
$row = pg_fetch_assoc($res);

```
The following requires less than 128 MB. I can't really explain why, but I am happy with it.
```
$res = pg_query("SELECT gzip(ST_AsGeoJSON(geom))");
$row = pg_fetch_assoc($res);
header('Content-Encoding: gzip');
echo pg_unescape_bytea($row['geojson']);
```
Big thanks to @pramsey for creating this extension, in the end I didn't even have to patch it.
