### ISSUE TITLE
Installing this on a windows server

### ISSUE THREAD

**Issue by infotek** [pramsey/pgsql-gzip#13]
What is the best method to installing this on a Windows PostgreSQL server?

**Comment by pramsey** [comment]
I'm afraid I don't have an answer, I'm not aware of anyone doing windows builds.

**Comment by hamdyahmed14** [comment]
@pramsey Thanks for your time . i just need to know how i create this extension in PostgreSQL installed in windows server . i tried with normal script but it give an error
