### ISSUE TITLE
building for wrong version of postgresql

### ISSUE THREAD

**Issue by Zedsquared** [pramsey/pgsql-gzip#16]
I have two versions of postgresql on my ubunto 22.04 server: v16 and V15. I want to build the extension for V15, but make  and make install will only build and install the extension for postgres V16.
Is there a way of specifying the build target?

Many thanks,
         Robin.

**Comment by pramsey** [comment]
Find the `pg_config` associated with the v15 install (maybe `/usr/pgsql-15/bin`?) and then set your `PATH` to put that directory first. 
```
export PATH=/usr/pgsql-15/bin:$PATH
```
the build/install process should then pick up the alternate information it needs to build against the v15 install.
