### ISSUE TITLE
Please do a version release, source only is ok

### ISSUE THREAD

**Issue by nyurik** [pramsey/pgsql-gzip#2]
@pramsey when you have a sec, could you tag the current git version as some sort of a release, e.g. v0.1.0?  This way when using it I can refer to it by a semantic name rather than just a hash, e.g. in a dockefile.  Thanks!

Steps: click releases, create new release, add a version, publish :)

**Comment by pramsey** [comment]
Done https://github.com/pramsey/pgsql-gzip/releases/tag/v1.0.0
