### ISSUE TITLE
Clarify build requirements

### ISSUE THREAD

**Issue by nyurik** [pramsey/pgsql-gzip#4]
I was not able to build the extension on Ubuntu 19.10 until I installed `postgresql-server-dev-all`. Is that the minimal requirement, or should it be `libpq-dev` or some other dep?  I would love to update the README, but not sure what is the correct dep here. Thx!

**Comment by pramsey** [comment]
There would be the pgsql server headers so that package sounds right, and also the zlib headers (zlib-dev?). That should be it.

**Comment by nyurik** [comment]
Thanks, I addressed it in #5, so closing this.
